### PR TITLE
Add sparc64 support for OpenBSD

### PR DESCRIPTION
**Pull request by bsdkurt**
Tested on OpenBSD current. Passes most tier1 test cases.

### CODE REVIEW

**Review by battleblow — APPROVED** [review]
LGTM.  Are you planning to forward port to 11 at all?

**Comment by bsdkurt** [comment]
Thank you Greg for the review. I’ll forward port this to 11 and either 16 or 17 if branched, but I’d like to see how well it does with our bulk build and sparc64 Java packages before doing that. 

There’s at least one bug that I’d like to squash first too, but gdb is crashing while running java. I may get side tracked updating gdb so I can debug things.

**Comment by battleblow** [comment]
> Thank you Greg for the review. I’ll forward port this to 11 and either 16 or 17 if branched, but I’d like to see how well it does with our bulk build and sparc64 Java packages before doing that.
> 
> There’s at least one bug that I’d like to squash first too, but gdb is crashing while running java. I may get side tracked updating gdb so I can debug things.

Thanks Kurt.  Be aware that Oracle have removed all sparc support from the tree for 16 (I think) and 17 (for sure).  So adding it back in for them is going to be a lot of work.  11 should be safe though.

**Comment by bsdkurt** [comment]
> Thanks Kurt. Be aware that Oracle have removed all sparc support from the tree for 16 (I think) and 17 (for sure). So adding it back in for them is going to be a lot of work. 11 should be safe though.

I wasn't aware of that. Thanks for the heads up.

**Pull request merged**
