### PR TITLE
Fix registers for FreeBSD/powerpc64

### PR DESCRIPTION
**Pull request by pkubaj**
I created a PR with older version of the patch, which uses Linux register naming.

### CODE REVIEW

**Comment by pkubaj** [comment]
Hm, building devel/jna port with such compiled openjdk8 fails on head:
`Error: failed /usr/local/openjdk8/jre/lib/ppc64/server/libjvm.so, because /usr/local/openjdk8/jre/lib/ppc64/server/libjvm.so: Undefined symbol "_ZN14ArrayAllocatorImL10MemoryType7EE4freeEv"`

But it works on 12.2. Any ideas?

**Comment by pkubaj** [comment]
And after disabling jfr:
`Error: failed /usr/local/openjdk8/jre/lib/ppc64/server/libjvm.so, because /usr/local/openjdk8/jre/lib/ppc64/server/libjvm.so: Undefined symbol "_ZN5frameC1EPlPh"`

**Review by battleblow — APPROVED** [review]

**Comment by battleblow** [comment]
The latter looks a bit like some problems that arm6/7 has, but I'll need to fire up my PPC box to try and look a bit more.

**Comment by battleblow** [comment]
Hmmm, it compiles and runs ok for me.  11.x with the builtin gcc 4.2.1

What's the FreeBSD version you see it on and what compiler are you using?

**Comment by pkubaj** [comment]
It builds fine on 12 for me as well. The problem happens on head, which uses Clang 11 and ELFv2.

**Comment by pkubaj** [comment]
I just verified that if you remove my patches AND disable jfr, things work again.

**Comment by battleblow** [comment]
So should we back out both of these commits?

**Comment by pkubaj** [comment]
Yes, they should be backed out for now.

**Pull request merged**
